### ISSUE TITLE
Can Azure Function be triggered for connect/disconnect of a client

### ISSUE THREAD

**Issue by PalashBorhan** [Azure/azure-functions-signalrservice-extension#54]
Not having the notification of connect/disconnect is actually a problem to use serverless for many use cases.

**Comment by Arash-Sabet** [comment]
@PalashBorhan I don't think if Azure Function would serve that purpose at all. Such a task is delegated to hubs.

**Comment by ErikAndreas** [comment]
Agreeing with @PalashBorhan, I'd like to be able to act on connect/disconnect [events](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2#handle-events-for-a-connection) on the hub. Now there seems to be no way, in/with a function, to act on user disconnect. I guess this relates to receiving messages from clients as well. We'd need a SignalR trigger for functions (like the Storage Queue trigger) being able to receive both client messages and (hub) events.

**Comment by Arash-Sabet** [comment]
@ErikAndreas I don't think if one should expect such functionality from the hub wrapped by Azure Functions. It implies that you'd want to override the default behavior of the hub hosted implicitly by Azure Functions. If that's the case, you need to do away from functions and just stick with the regular signalR hub implementation.

**Comment by ErikAndreas** [comment]
@Arash-Sabet I'm not following your reasoning?! I want something similar in az funcs as I do with oob azure signalr service but packaged for az funcs. I'd think a SignalR Trigger for az funcs would make a lot of sense. Why shouldn't I be able to get notified of e.g user disconnect just because I'm running az funcs? It's not that I'm "expecting", I'd just like to see the feats of az funcs evolve.

**Comment by anthonychu** [comment]
I agree with you @PalashBorhan @ErikAndreas. This would be great functionality to add. It would expose connection IDs to Azure Functions (allowing us to add connectionId to a group instead of userId and to manage groups when a connection is established). It would also make it possible to build apps that need to track user presence.

It would be really useful if you can provide some details on how you would use this. It would help us prioritize this work. Thanks!

**Comment by Arash-Sabet** [comment]
@anthonychu @PalashBorhan @ErikAndreas Sounds like that events like OnConnected and OnDisconnected would be needed in this case to be able to track users' connections.

**Comment by anthonychu** [comment]
Correct. They would trigger a function and pass along the connection ID and user ID (if present). That function can use output bindings to manage groups, track presence, etc.

The functions can be triggered by webhook, Event Grid, Event Hubs, or some other mechanism. This will need to be debated.

Having the mechanism in place will also allow functions to receive messages sent from clients to the “hub” using the SignalR connection instead of separate HTTP posts.

**Comment by Arash-Sabet** [comment]
@anthonychu Sounds like a nice architecture! I liked it! 👍

**Comment by ErikAndreas** [comment]
@anthonychu I think you covered the main use scenarios already : ) Track user presence  (onconnect/disconnect) but also having functions triggered by messages from clients (via hub). I have two actual use cases (building a chat where users need to "wait in line" for a SME to chat with, i.e one chat party is a limited "resource")
1a - user disconnect) users might leave while waiting
1b - user connect/disconnect) users might have (temporary) connectivity problems and I'd like to show some status around this
2 - user send via hub) light weight signalling not needed to be passed through http posts (putting load on backend) (sent from client via hub to other participants in chat) such as "user nnn is typing"

**Comment by PalashBorhan** [comment]
@anthonychu Yes look like you covered the use case pretty much. Needed to track the presence of a user to deliver a message or event.

Thanks for having this implemented.

**Comment by PalashBorhan** [comment]
Just wanted to check, if there is any ETA or expectation on this. Thanks.

**Comment by DanielClausen** [comment]
I have this same use case, I need to be aware if the user is online or not and has an active session.  I've not been able to find a sufficient workaround other then to implement a simple polling mechanism and a timer to clean up any users that hasn't checked in recently.  Having a function that can respond to a disconnect would make this dramatically easier.

**Comment by zackliu** [comment]
Now you can leverage Event Grid trigger to get connect/disconnect events. Here's [the sample](https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/EventGridIntegration).
